Common_Messages:
  APPLICATION_ERROR: "Something went wrong"
  USER_GROUP_NOT_FOUND: "User group not found for user"
  DATA_DELETED_SUCCESSFULLY: "Data deleted successfully"

APP_USER:
    ID_NOT_NULL: "AppUser ID must not be null"
    USER_NAME_NOT_NULL: "AppUser name must not be null"
    PASSWORD_NOT_NULL: "AppUser password must not be null"
    EMAIL_NOT_NULL: "AppUser email must not be null"
    USER_NAME_DUPLICATE: "AppUser name %1$s already exists"
    EMAIL_DUPLICATE: "AppUser email %1$s already exists"
    USER_NOT_FOUND: "AppUser not found"

CONNECTOR:
  ID_NOT_FOUND: "Connector ID %1$s not found"
  DUPLICATE_CONNECTOR: "Duplicate connector"